import { main } from './alg/StudentDistribution';
import { getItems } from './data/Items';
import { getStudents } from './data/Students';
import { getPolls } from './data/Polls';
import { getProject } from './data/Projects';
// import { findItemsByStudentId } from './alg/TimeDistribution/Utils';
const project = getProject();
const projectId = project._id;
console.time();
main(getItems(projectId), getStudents(projectId), project, getPolls(projectId));
console.timeEnd();
